// Generated by https://quicktype.io

export interface Package {
    id:           number;
    name:         string;
    minWeight:    number;
    maxWeight:    number | null;
    priceFormula: string;
}
