// Generated by https://quicktype.io

export interface Send {
    id:                    number;
    packageType:           number;
    weight:                number;
    recipient:             string;
    destinationPostalCode: number;
    companyId:             number;
}
