// Generated by https://quicktype.io

export interface User {
    id:       number;
    username: string;
    email:    string;
    role:     Role;
}

export enum Role {
    Admin = "Admin",
    Worker = "Worker"
}